### ISSUE TITLE
Add Animation Component

### ISSUE THREAD

**Issue by rylankasitz** [zachwood0s/GameEngineRemake#17]

**Comment by zachwood0s** [comment]
You can select just a regular issue at the bottom under the 2 choices so it doesn't have all the template text

**Comment by rylankasitz** [comment]
@zachwood0s what do you think about having the animation somewhat similar to the input manager where you create global animations from sprite sheets / series of textures and reference them in the animation component where you can make them run on a certain events.

**Comment by zachwood0s** [comment]
@rylankasitz Would you still be able to control some of the properties of the animation from within the entities component? What are you think is the advantage of doing it that way vs. just having it all stored in the component? I'm fine with it either way, I'm just curious.

**Comment by rylankasitz** [comment]
@zachwood0s I thought it might be helpful if say you wanted to have an explosion animation on two different entities you wouldn't have to recreate the component is would be already defined and you could just reference it in the component.

I was thinking that the component part would be more of an animation handler and you would reference the animations by name. You could accesses all of the animations the component is using in the script or you could just reference the animations from the global animation manager. 

I I'm not sure if that is the best way to do it but is was just an Idea I had.

**Comment by zachwood0s** [comment]
@rylankasitz Ah okay that makes sense. So essentially what would be stored globally would just be the sequence of textures that can be referenced and the components/systems would do all the managing of which image to show, hide, etc. ?

**Comment by rylankasitz** [comment]
@zachwood0s Yeah the global animation would look something like this:
{
"Name" :  "Character_Walk",
"FileLocation" : "directory/" or "spritsheet.png",
// If sprite sheet
"SpriteSize": "[100,100]",
"SubSheet":"[0,0,500,200]"
}
and the animation component would reference that animation by its name.

Its basically so the user doesn't have to redefine an animation if he wants to use it for different entities.

**Comment by zachwood0s** [comment]
@rylankasitz Yeah I think that's a good idea
